set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",*:Smulx=\E[4::%p1%dm"
set -ga terminal-overrides ",*:Setulc=\E[58::2::%p1%d;%p2%d;%p3%dm"
set -g focus-events on
set -sg escape-time 0
set -g history-limit 50000
set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -s extended-keys on
